const WORLD = {

tileSize: 48,

towns: [

{
name: "Evergreen Town",
x: 8,
y: 8
},

{
name: "Stonehaven City",
x: 25,
y: 12
},

{
name: "Crystal Port",
x: 42,
y: 18
}

],

map: [

"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"

]

};