const WORLD = {

tileSize: 48,

towns: [

{
name: “Evergreen Town”,
x: 8,
y: 8,
type: “starter”
},

{
name: “Stonehaven City”,
x: 25,
y: 12,
type: “city”
},

{
name: “Crystal Port”,
x: 42,
y: 18,
type: “port”
}

],

npcs: [

{
name: “Professor Alder”,
x: 10,
y: 8,
message: “Welcome to Mythic Realms! Choose your first creature.”
},

{
name: “Arena Guard”,
x: 15,
y: 10,
message: “Only strong trainers earn badges.”
},

{
name: “Merchant”,
x: 6,
y: 10,
message: “I sell supplies for adventurers.”
}

],

buildings: [

{
type: “house”,
x: 6,
y: 7
},

{
type: “house”,
x: 11,
y: 7
},

{
type: “lab”,
x: 9,
y: 11
},

{
type: “arena”,
x: 15,
y: 8
}

],

map: [

“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGTTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGTTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGTTTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR”,
“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”,
“WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG”

]

};
