const WORLD = {

tileSize: 48,

towns: [

{
name: "Evergreen Town",
x: 8,
y: 8,
type: "starter"
},

{
name: "Stonehaven City",
x: 25,
y: 12,
type: "city"
},

{
name: "Crystal Port",
x: 42,
y: 18,
type: "port"
}

],

npcs: [

{
name: "Professor Alder",
x: 10,
y: 8,
message: "Welcome to Mythic Realms!"
}

],
name: "Stonehaven City",
x: 25,
y: 12
},

{
name: "Crystal Port",
x: 42,
y: 18
}

],

map: [

"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGTTTTTTTTGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
"WWWWWWWWWWWWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG"

]

};